apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  namespace: web-app-namespace
  labels:
    app: nginx-deployment
    service: nginx-clusterip
spec:
  type: ClusterIP
  selector:
    app: nginx-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
